export const VERIFY_LOGIN_OTP = "VERIFY_LOGIN_OTP";
export const VERIFY_LOGIN_OTP_REQUEST = "VERIFY_LOGIN_OTP_REQUEST";
export const VERIFY_LOGIN_OTP_SUCCESS = "VERIFY_LOGIN_OTP_SUCCESS";
export const VERIFY_LOGIN_OTP_FAILURE = "VERIFY_LOGIN_OTP_FAILURE";


export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const UPDATE_APP_DEVICE_STATE = "UPDATE_APP_DEVICE_STATE";
