export const FETCH_COMMUNITIES = "FETCH_COMMUNITIES";
export const FETCH_COMMUNITIES_REQUEST = "FETCH_COMMUNITIES_REQUEST";
export const FETCH_COMMUNITIES_SUCCESS = "FETCH_COMMUNITIES_SUCCESS";
export const FETCH_COMMUNITIES_FAILURE = "FETCH_COMMUNITIES_FAILURE";

export const FETCH_COMMUNITY = "FETCH_COMMUNITY";
export const FETCH_COMMUNITY_REQUEST = "FETCH_COMMUNITY_REQUEST";
export const FETCH_COMMUNITY_SUCCESS = "FETCH_COMMUNITY_SUCCESS";
export const FETCH_COMMUNITY_FAILURE = "FETCH_COMMUNITY_FAILURE";


export const FETCH_MESSAGE_BUDDIES: string = "FETCH_MESSAGE_BUDDIES";
export const FETCH_MESSAGE_BUDDIES_REQUEST = "FETCH_MESSAGE_BUDDIES_REQUEST";
export const FETCH_MESSAGE_BUDDIES_SUCCESS = "FETCH_MESSAGE_BUDDIES_SUCCESS";
export const FETCH_MESSAGE_BUDDIES_FAILURE = "FETCH_MESSAGE_BUDDIES_FAILURE";

export const SET_ACTIVE_BUDDY: string = "SET_ACTIVE_BUDDY";
export const SET_ACTIVE_BUDDY_MESSAGE: string = "SET_ACTIVE_BUDDY_MESSAGE";
