export const FETCH_COMMUNITIES = "FETCH_COMMUNITIES";
export const FETCH_COMMUNITIES_REQUEST: string = "FETCH_COMMUNITIES_REQUEST";
export const FETCH_COMMUNITIES_SUCCESS: string = "FETCH_COMMUNITIES_SUCCESS";
export const FETCH_COMMUNITIES_FAILURE: string = "FETCH_COMMUNITIES_FAILURE";

export const FETCH_COMMUNITY: string = "FETCH_COMMUNITY";
export const FETCH_COMMUNITY_REQUEST: string = "FETCH_COMMUNITY_REQUEST";
export const FETCH_COMMUNITY_SUCCESS: string = "FETCH_COMMUNITY_SUCCESS";
export const FETCH_COMMUNITY_FAILURE: string = "FETCH_COMMUNITY_FAILURE";

export const FETCH_CHAT_BUDDIES: string = "FETCH_CHAT_BUDDIES";
export const FETCH_CHAT_BUDDIES_REQUEST: string = "FETCH_CHAT_BUDDIES_REQUEST";
export const FETCH_CHAT_BUDDIES_SUCCESS: string = "FETCH_CHAT_BUDDIES_SUCCESS";
export const FETCH_CHAT_BUDDIES_FAILURE: string = "FETCH_CHAT_BUDDIES_FAILURE";

export const SET_ACTIVE_CHAT: string = "SET_ACTIVE_CHAT";
export const SET_ACTIVE_BUDDY_MESSAGE: string = "SET_ACTIVE_BUDDY_MESSAGE";

export const SEND_MESSAGE: string = "SEND_MESSAGE";
export const SEND_MESSAGE_REQUEST: string = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS: string = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE: string = "SEND_MESSAGE_FAILURE";

export const ADD_ACTIVE_CHAT_MESSAGE: string = "ADD_ACTIVE_CHAT_MESSAGE";
