export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const FETCH_USER_DETAILS_REQUEST: string = "FETCH_USER_DETAILS_REQUEST";
export const FETCH_USER_DETAILS_SUCCESS: string = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE: string = "FETCH_USER_DETAILS_FAILURE";

export const SET_USER_DETAILS: string = "SET_USER_DETAILS";
