export const VERIFY_LOGIN_OTP = "VERIFY_LOGIN_OTP";
export const VERIFY_LOGIN_OTP_REQUEST = "VERIFY_LOGIN_OTP_REQUEST";
export const VERIFY_LOGIN_OTP_SUCCESS = "VERIFY_LOGIN_OTP_SUCCESS";
export const VERIFY_LOGIN_OTP_FAILURE = "VERIFY_LOGIN_OTP_FAILURE";

export const RESEND_LOGIN_OTP = "RESEND_LOGIN_OTP";
export const RESEND_LOGIN_OTP_REQUEST = "RESEND_LOGIN_OTP_REQUEST";
export const RESEND_LOGIN_OTP_SUCCESS = "RESEND_LOGIN_OTP_SUCCESS";
export const RESEND_LOGIN_OTP_FAILURE = "RESEND_LOGIN_OTP_FAILURE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const RESET_LOGIN_AUTH: string = "RESET_LOGIN_AUTH";
export const SET_USER_AUTHENTICATE = "SET_USER_AUTHENTICATE";

export const SET_LOGIN_STATE: string = "SET_LOGIN_STATE";
export const SET_AUTH_ERROR: string = "SET_AUTH_ERROR";
