export const VERIFY_LOGIN_OTP = "VERIFY_LOGIN_OTP";
export const VERIFY_LOGIN_OTP_REQUEST = "VERIFY_LOGIN_OTP_REQUEST";
export const VERIFY_LOGIN_OTP_SUCCESS = "VERIFY_LOGIN_OTP_SUCCESS";
export const VERIFY_LOGIN_OTP_FAILURE = "VERIFY_LOGIN_OTP_FAILURE";

export const RESEND_LOGIN_OTP = "RESEND_LOGIN_OTP";
export const RESEND_LOGIN_OTP_REQUEST = "RESEND_LOGIN_OTP_REQUEST";
export const RESEND_LOGIN_OTP_SUCCESS = "RESEND_LOGIN_OTP_SUCCESS";
export const RESEND_LOGIN_OTP_FAILURE = "RESEND_LOGIN_OTP_FAILURE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const CHECK_USER_AUTH = "CHECK_USER_AUTH";
export const CHECK_USER_AUTH_REQUEST = "CHECK_USER_AUTH_REQUEST";
export const CHECK_USER_AUTH_SUCCESS = "CHECK_USER_AUTH_SUCCESS";
export const CHECK_USER_AUTH_FAILURE = "CHECK_USER_AUTH_FAILURE";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const RESET_LOGIN_AUTH: string = "RESET_LOGIN_AUTH";
export const SET_USER_AUTHENTICATE = "SET_USER_AUTHENTICATE";

export const SET_LOGIN_STATE: string = "SET_LOGIN_STATE";
export const SET_AUTH_ERROR: string = "SET_AUTH_ERROR";

export const RESET_USER_AUTH = "RESET_USER_AUTH";
export const SET_ACCESS_TOKEN_EXISTENCE: string = "SET_ACCESS_TOKEN_EXISTENCE";

export const SET_SIGN_UP_STEP_ACTIVE_INDEX: string =
  "SET_SIGN_UP_STEP_ACTIVE_INDEX";
export const MOVE_SIGN_UP_STEP_ACTIVE_INDEX: string =
  "MOVE_SIGN_UP_STEP_ACTIVE_INDEX";

export const SET_SIGN_UP_ACCOUNT_DETAILS: string =
  "SET_SIGN_UP_ACCOUNT_DETAILS";
export const SET_SIGN_UP_PASSWORD_DETAILS: string =
  "SET_SIGN_UP_PASSWORD_DETAILS";
export const SET_SIGN_UP_PERSONAL_DETAILS: string =
  "SET_SIGN_UP_PERSONAL_DETAILS";
export const SET_SIGN_UP_ADDRESS_DETAILS: string =
  "SET_SIGN_UP_ADDRESS_DETAILS";
export const SET_SIGN_UP_CONTACT_DETAILS: string =
  "SET_SIGN_UP_CONTACT_DETAILS";

export const CHECK_SIGN_UP_EMAIL: string = "CHECK_SIGN_UP_EMAIL";
export const CHECK_SIGN_UP_EMAIL_REQUEST: string =
  "CHECK_SIGN_UP_EMAIL_REQUEST";
export const CHECK_SIGN_UP_EMAIL_SUCCESS: string =
  "CHECK_SIGN_UP_EMAIL_SUCCESS";
export const CHECK_SIGN_UP_EMAIL_FAILURE: string =
  "CHECK_SIGN_UP_EMAIL_FAILURE";
  
  export const SIGN_UP_USER = "SIGN_UP_USER";
  export const SIGN_UP_USER_REQUEST = "SIGN_UP_USER_REQUEST";
  export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
  export const SIGN_UP_USER_FAILURE = "SIGN_UP_USER_FAILURE";